return {
	{
		no = 1,
		word = "cat",
		ja = "猫",
		es = "gato",
		fr = "chat",
		de = "Katze",
		tl = "pusa",
		category1 = "n",
		category2 = { ja = "生き物", es = "ser vivo", fr = "être vivant", de = "Lebewesen", tl = "nilalang" },
	},
	{
		no = 2,
		word = "dog",
		ja = "犬",
		es = "perro",
		fr = "chien",
		de = "Hund",
		tl = "aso",
		category1 = "n",
		category2 = { ja = "生き物", es = "ser vivo", fr = "être vivant", de = "Lebewesen", tl = "nilalang" },
	},
	{
		no = 3,
		word = "run",
		ja = "走る",
		es = "correr",
		fr = "courir",
		de = "laufen",
		tl = "tumakbo",
		category1 = "v",
		category2 = { ja = "行動", es = "acción", fr = "action", de = "Handlung", tl = "kilos" },
	},
	{
		no = 4,
		word = "big",
		ja = "大きい",
		es = "grande",
		fr = "grand",
		de = "groß",
		tl = "malaki",
		category1 = "a",
		category2 = { ja = "様子", es = "aspecto", fr = "apparence", de = "Aussehen", tl = "itsura" },
	},
	{
		no = 5,
		word = "sun",
		ja = "太陽",
		es = "sol",
		fr = "soleil",
		de = "Sonne",
		tl = "araw",
		category1 = "n",
		category2 = { ja = "自然", es = "naturaleza", fr = "nature", de = "Natur", tl = "kalikasan" },
	},
	{
		no = 6,
		word = "book",
		ja = "本",
		es = "libro",
		fr = "livre",
		de = "Buch",
		tl = "aklat",
		category1 = "n",
		category2 = { ja = "モノ", es = "objeto", fr = "objet", de = "Gegenstand", tl = "bagay" },
	},
	{
		no = 7,
		word = "eat",
		ja = "食べる",
		es = "comer",
		fr = "manger",
		de = "essen",
		tl = "kumain",
		category1 = "v",
		category2 = { ja = "行動", es = "acción", fr = "action", de = "Handlung", tl = "kilos" },
	},
	{
		no = 8,
		word = "red",
		ja = "赤",
		es = "rojo",
		fr = "rouge",
		de = "rot",
		tl = "pula",
		category1 = "o",
		category2 = { ja = "色", es = "color", fr = "couleur", de = "Farbe", tl = "kulay" },
	},
	{
		no = 9,
		word = "water",
		ja = "水",
		es = "agua",
		fr = "eau",
		de = "Wasser",
		tl = "tubig",
		category1 = "n",
		category2 = { ja = "自然", es = "naturaleza", fr = "nature", de = "Natur", tl = "kalikasan" },
	},
	{
		no = 10,
		word = "happy",
		ja = "幸せ",
		es = "feliz",
		fr = "heureux",
		de = "glücklich",
		tl = "masaya",
		category1 = "a",
		category2 = { ja = "気持ち", es = "sentimiento", fr = "sentiment", de = "Gefühl", tl = "damdamin" },
	},
}
