return {
	{
		name = "Banana_C1",
		centerX = 9858.5,
		centerZ = -17.0,
		sizeXZ = 118.9,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = true,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C2",
		centerX = 9863.5,
		centerZ = 21.0,
		sizeXZ = 105.3,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C3",
		centerX = 9914.5,
		centerZ = 72.0,
		sizeXZ = 104.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C4",
		centerX = 9909.5,
		centerZ = 78.0,
		sizeXZ = 99.9,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C5",
		centerX = 9900.5,
		centerZ = 37.0,
		sizeXZ = 96.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C6",
		centerX = 9940.5,
		centerZ = 109.0,
		sizeXZ = 87.7,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C7",
		centerX = 9896.5,
		centerZ = 37.0,
		sizeXZ = 82.3,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C8",
		centerX = 9932.5,
		centerZ = 100.0,
		sizeXZ = 81.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C9",
		centerX = 9934.5,
		centerZ = 109.0,
		sizeXZ = 79.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C10",
		centerX = 9896.5,
		centerZ = 15.0,
		sizeXZ = 76.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C11",
		centerX = 9922.5,
		centerZ = 95.0,
		sizeXZ = 75.1,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C12",
		centerX = 9889.5,
		centerZ = -9.0,
		sizeXZ = 74.0,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C13",
		centerX = 9909.5,
		centerZ = 14.0,
		sizeXZ = 73.1,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C14",
		centerX = 9943.5,
		centerZ = 112.0,
		sizeXZ = 72.3,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C15",
		centerX = 9879.5,
		centerZ = -37.0,
		sizeXZ = 71.2,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C16",
		centerX = 9948.5,
		centerZ = 101.0,
		sizeXZ = 70.9,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C17",
		centerX = 9956.5,
		centerZ = 107.0,
		sizeXZ = 69.9,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C18",
		centerX = 9983.5,
		centerZ = 124.0,
		sizeXZ = 65.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C19",
		centerX = 9974.5,
		centerZ = 113.0,
		sizeXZ = 63.0,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C20",
		centerX = 9999.5,
		centerZ = 127.0,
		sizeXZ = 60.0,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C21",
		centerX = 9968.5,
		centerZ = 112.0,
		sizeXZ = 59.7,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C22",
		centerX = 9990.5,
		centerZ = 126.0,
		sizeXZ = 59.1,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C23",
		centerX = 10017.5,
		centerZ = 127.0,
		sizeXZ = 55.7,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C24",
		centerX = 9966.5,
		centerZ = 93.0,
		sizeXZ = 55.7,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C25",
		centerX = 10052.5,
		centerZ = 122.0,
		sizeXZ = 54.8,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C26",
		centerX = 10046.5,
		centerZ = 116.0,
		sizeXZ = 53.2,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C27",
		centerX = 10087.5,
		centerZ = 100.0,
		sizeXZ = 52.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C28",
		centerX = 10065.5,
		centerZ = 110.0,
		sizeXZ = 51.9,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C29",
		centerX = 9950.5,
		centerZ = 73.0,
		sizeXZ = 51.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C30",
		centerX = 9981.5,
		centerZ = 92.0,
		sizeXZ = 50.0,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C31",
		centerX = 10094.5,
		centerZ = 82.0,
		sizeXZ = 49.5,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C32",
		centerX = 10116.5,
		centerZ = 60.0,
		sizeXZ = 48.7,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C33",
		centerX = 9968.5,
		centerZ = 60.0,
		sizeXZ = 47.7,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C34",
		centerX = 10132.5,
		centerZ = 33.0,
		sizeXZ = 46.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C35",
		centerX = 9979.5,
		centerZ = 53.0,
		sizeXZ = 45.6,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 10,
		hillScale = 120,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C36",
		centerX = 10147.5,
		centerZ = 9.0,
		sizeXZ = 44.8,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C37",
		centerX = 10153.5,
		centerZ = -18.0,
		sizeXZ = 43.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C38",
		centerX = 9993.5,
		centerZ = 49.0,
		sizeXZ = 42.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 50,
		hillScale = 150,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C39",
		centerX = 9990.5,
		centerZ = 29.0,
		sizeXZ = 41.0,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 80,
		hillScale = 150,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C40",
		centerX = 10154.5,
		centerZ = -45.0,
		sizeXZ = 39.3,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C41",
		centerX = 10166.5,
		centerZ = -65.0,
		sizeXZ = 37.8,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C42",
		centerX = 10176.5,
		centerZ = -87.0,
		sizeXZ = 35.9,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C43",
		centerX = 10182.5,
		centerZ = -105.0,
		sizeXZ = 34.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C44",
		centerX = 10187.5,
		centerZ = -124.0,
		sizeXZ = 31.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C45",
		centerX = 10195.5,
		centerZ = -141.0,
		sizeXZ = 29.8,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C46",
		centerX = 10203.5,
		centerZ = -156.0,
		sizeXZ = 27.8,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C47",
		centerX = 10212.5,
		centerZ = -170.0,
		sizeXZ = 25.8,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C48",
		centerX = 10220.5,
		centerZ = -182.0,
		sizeXZ = 24.2,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C49",
		centerX = 10230.5,
		centerZ = -195.0,
		sizeXZ = 22.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "Banana_C50",
		centerX = 10240.5,
		centerZ = -205.0,
		sizeXZ = 20.4,
		baseY = 20,
		thickness = 40,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 1,
		seed = 1,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
}
