return {
	{
		name = "VerdantPlateau_C1",
		centerX = 3000,
		centerZ = 0,
		sizeXZ = 300,
		baseY = 8,
		thickness = 14,
		grid = 14,
		hillAmplitude = 6,
		hillScale = 160,
		seed = 41021,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "VerdantPlateau_C2",
		centerX = 3280,
		centerZ = -120,
		sizeXZ = 290,
		baseY = 8,
		thickness = 14,
		grid = 14,
		hillAmplitude = 6,
		hillScale = 160,
		seed = 51239,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "VerdantPlateau_C3",
		centerX = 2720,
		centerZ = -100,
		sizeXZ = 280,
		baseY = 8,
		thickness = 14,
		grid = 14,
		hillAmplitude = 6,
		hillScale = 160,
		seed = 63917,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
	{
		name = "VerdantPlateau_C4",
		centerX = 3000,
		centerZ = 260,
		sizeXZ = 270,
		baseY = 8,
		thickness = 14,
		grid = 14,
		hillAmplitude = 6,
		hillScale = 160,
		seed = 74288,
		generateOcean = false,
		baseMaterial = Enum.Material.Grass,
	},
}
