-- ReplicatedStorage/Islands/HokkaidoIslands
return {
	-- 中央部 --2935.0, 15.8, 1.4)
	{
		name = "Hokkaido_W0",
		centerX = 2935,
		centerZ = 1.4,
		sizeXZ = 40,
		baseY = 10,
		thickness = 40,
		grid = 2,
		hillAmplitude = 15,
		hillScale = 1,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_W1",
		centerX = 3000,
		centerZ = 0,
		sizeXZ = 160,
		baseY = 10,
		thickness = 40,
		grid = 3,
		hillAmplitude = 15,
		hillScale = 1,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_C1",
		centerX = 3080,
		centerZ = 0,
		sizeXZ = 160,
		baseY = 10,
		thickness = 40,
		grid = 3,
		hillAmplitude = 15,
		hillScale = 1,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_C2",
		centerX = 3160,
		centerZ = 0,
		sizeXZ = 160,
		baseY = 10,
		thickness = 40,
		grid = 3,
		hillAmplitude = 15,
		hillScale = 1,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_C3",
		centerX = 3240,
		centerZ = 0,
		sizeXZ = 160,
		baseY = 10,
		thickness = 40,
		grid = 3,
		hillAmplitude = 15,
		hillScale = 1,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_C4",
		centerX = 3320,
		centerZ = 0,
		sizeXZ = 160,
		baseY = 10,
		thickness = 40,
		grid = 3,
		hillAmplitude = 15,
		hillScale = 1,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_C5",
		centerX = 3400,
		centerZ = 0,
		sizeXZ = 160,
		baseY = 10,
		thickness = 40,
		grid = 3,
		hillAmplitude = 15,
		hillScale = 1,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_E1",
		centerX = 3480,
		centerZ = 0,
		sizeXZ = 160,
		baseY = 10,
		thickness = 40,
		grid = 2,
		hillAmplitude = 160,
		hillScale = 160,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},

	-- 北部
	{
		name = "Hokkaido_N1",
		centerX = 3080,
		centerZ = 80,
		sizeXZ = 160,
		baseY = 10,
		thickness = 10,
		grid = 3,
		hillAmplitude = 1,
		hillScale = 500,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_N2",
		centerX = 3160,
		centerZ = 80,
		sizeXZ = 160,
		baseY = 10,
		thickness = 10,
		grid = 3,
		hillAmplitude = 1,
		hillScale = 500,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_N3",
		centerX = 3240,
		centerZ = 80,
		sizeXZ = 160,
		baseY = 10,
		thickness = 10,
		grid = 3,
		hillAmplitude = 1,
		hillScale = 500,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_N4",
		centerX = 3320,
		centerZ = 80,
		sizeXZ = 160,
		baseY = 10,
		thickness = 10,
		grid = 3,
		hillAmplitude = 1,
		hillScale = 500,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},

	-- 北東部（知床）
	{
		name = "Hokkaido_NE1",
		centerX = 3320,
		centerZ = 160,
		sizeXZ = 160,
		baseY = 10,
		thickness = 10,
		grid = 3,
		hillAmplitude = 10,
		hillScale = 500,
		seed = 50000,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_NE2",
		centerX = 3400,
		centerZ = 160,
		sizeXZ = 160,
		baseY = 10,
		thickness = 10,
		grid = 3,
		hillAmplitude = 10,
		hillScale = 500,
		seed = 50000,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},

	-- 南部
	{
		name = "Hokkaido_S1",
		centerX = 3160,
		centerZ = -80,
		sizeXZ = 200,
		baseY = 10,
		thickness = 10,
		grid = 2,
		hillAmplitude = 120,
		hillScale = 100,
		seed = 50000,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_S2",
		centerX = 3240,
		centerZ = -80,
		sizeXZ = 200,
		baseY = 10,
		thickness = 10,
		grid = 1,
		hillAmplitude = 200,
		hillScale = 200,
		seed = 50000,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},

	-- 南西部（渡島）
	{
		name = "Hokkaido_SW1",
		centerX = 3080,
		centerZ = -160,
		sizeXZ = 160,
		baseY = 10,
		thickness = 10,
		grid = 1,
		hillAmplitude = 300,
		hillScale = 160,
		seed = 50000,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_SW2",
		centerX = 3160,
		centerZ = -160,
		sizeXZ = 160,
		baseY = 10,
		thickness = 10,
		grid = 1,
		hillAmplitude = 400,
		hillScale = 20,
		seed = 50000,
		generateOcean = true,
		baseMaterial = Enum.Material.LeafyGrass,
		oceanRadius = 2000,
	},
}
