return {
	{
		name = "Hokkaido_01",
		centerX = 482,
		centerZ = 449,
		sizeXZ = 402,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 50,
		hillScale = 40,
		-- hillAmplitude = 1,
		-- hillScale = 100,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_02",
		centerX = 744,
		centerZ = 450,
		sizeXZ = 197,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_03",
		centerX = 487,
		centerZ = 643,
		sizeXZ = 170,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_04",
		centerX = 393,
		centerZ = 304,
		sizeXZ = 170,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_05",
		centerX = 460,
		centerZ = 280,
		sizeXZ = 170,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_06",
		centerX = 322,
		centerZ = 554,
		sizeXZ = 157,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_07",
		centerX = 210,
		centerZ = 578,
		sizeXZ = 145,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_07A",
		centerX = 210,
		centerZ = 578,
		sizeXZ = 70,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 50,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.Mud,
	},
	{
		name = "Hokkaido_08",
		centerX = 398,
		centerZ = 194,
		sizeXZ = 145,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_09",
		centerX = 652,
		centerZ = 384,
		sizeXZ = 143,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_10",
		centerX = 634,
		centerZ = 524,
		sizeXZ = 123,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_11",
		centerX = 374,
		centerZ = 126,
		sizeXZ = 112,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_12",
		centerX = 346,
		centerZ = 74,
		sizeXZ = 91,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_13",
		centerX = 152,
		centerZ = 593,
		sizeXZ = 91,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_14",
		centerX = 138,
		centerZ = 761,
		sizeXZ = 91,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_15",
		centerX = 92,
		centerZ = 633,
		sizeXZ = 83,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_16",
		centerX = 754,
		centerZ = 524,
		sizeXZ = 79,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_17",
		centerX = 804,
		centerZ = 514,
		sizeXZ = 79,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_18",
		centerX = 68,
		centerZ = 689,
		sizeXZ = 77,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_19",
		centerX = 213,
		centerZ = 654,
		sizeXZ = 68,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_20",
		centerX = 383,
		centerZ = 626,
		sizeXZ = 68,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_21",
		centerX = 531,
		centerZ = 715,
		sizeXZ = 68,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_22",
		centerX = 422,
		centerZ = 660,
		sizeXZ = 68,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_23",
		centerX = 102,
		centerZ = 734,
		sizeXZ = 68,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_24",
		centerX = 102,
		centerZ = 788,
		sizeXZ = 68,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_25",
		centerX = 83,
		centerZ = 832,
		sizeXZ = 68,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_26",
		centerX = 298,
		centerZ = 432,
		sizeXZ = 68,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_27",
		centerX = 332,
		centerZ = 105,
		sizeXZ = 68,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_28",
		centerX = 155,
		centerZ = 524,
		sizeXZ = 56,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_29",
		centerX = 809,
		centerZ = 370,
		sizeXZ = 56,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_30",
		centerX = 255,
		centerZ = 626,
		sizeXZ = 56,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_31",
		centerX = 129,
		centerZ = 501,
		sizeXZ = 48,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_32",
		centerX = 850,
		centerZ = 492,
		sizeXZ = 48,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_33",
		centerX = 184,
		centerZ = 776,
		sizeXZ = 48,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_34",
		centerX = 279,
		centerZ = 408,
		sizeXZ = 48,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_35",
		centerX = 344,
		centerZ = 241,
		sizeXZ = 48,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_36",
		centerX = 346,
		centerZ = 621,
		sizeXZ = 47,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_37",
		centerX = 880,
		centerZ = 492,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_38",
		centerX = 902,
		centerZ = 481,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_39",
		centerX = 830,
		centerZ = 338,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_40",
		centerX = 844,
		centerZ = 315,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_41",
		centerX = 858,
		centerZ = 291,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_42",
		centerX = 706,
		centerZ = 524,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_43",
		centerX = 214,
		centerZ = 789,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_44",
		centerX = 66,
		centerZ = 859,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_45",
		centerX = 44,
		centerZ = 647,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_46",
		centerX = 544,
		centerZ = 751,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_47",
		centerX = 288,
		centerZ = 483,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_48",
		centerX = 346,
		centerZ = 21,
		sizeXZ = 29,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_49",
		centerX = 320,
		centerZ = 41,
		sizeXZ = 29,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},

	{
		name = "Hokkaido_50",
		centerX = 540.2,
		centerZ = 726.6,
		sizeXZ = 30,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 60,
		hillScale = 30,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.Mud,
	},

	{
		name = "Hokkaido_51",
		centerX = 519.7,
		centerZ = 702.7,
		sizeXZ = 60,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 60,
		hillScale = 40,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.Mud,
	},

	{
		name = "Hokkaido_52",
		centerX = 504.7,
		centerZ = 669.6,
		sizeXZ = 80,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 60,
		hillScale = 60,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.Mud,
	},

	{
		name = "Hokkaido_53",
		centerX = 486.1,
		centerZ = 628.6,
		sizeXZ = 60,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 60,
		hillScale = 80,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.Mud,
	},

	{
		name = "Hokkaido_54",
		centerX = 489.9,
		centerZ = 581.3,
		sizeXZ = 100,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 80,
		hillScale = 60,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.Mud,
	},

	{
		name = "Hokkaido_55",
		centerX = 499.8,
		centerZ = 514.1,
		sizeXZ = 120,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 110,
		hillScale = 80,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.Mud,
	},

	{
		name = "Hokkaido_56",
		centerX = 512.3,
		centerZ = 470.7,
		sizeXZ = 170,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 125,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.Mud,
	},
	{
		name = "Hokkaido_57",
		centerX = 539.2,
		centerZ = 413.1,
		sizeXZ = 120,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 100,
		hillScale = 160,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.Mud,
	},
	{
		name = "Hokkaido_58",
		centerX = 388.6,
		centerZ = 622.3,
		sizeXZ = 100,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = true,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Hokkaido_59",
		centerX = 512.8,
		centerZ = 472.1,
		sizeXZ = 36,
		baseY = 88,
		thickness = 20,
		grid = 2,
		hillAmplitude = 30,
		hillScale = 7,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.Snow,
	},
	{ --{665.2, 23.6, 446.7
		name = "Hokkaido_60",
		centerX = 665.2,
		centerZ = 446.7,
		sizeXZ = 45,
		baseY = 10,
		thickness = 20,
		grid = 2,
		hillAmplitude = 40,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
}
