--- Islands ---
return {
	{
		name = "ContinentKyushu_C1",
		centerX = 2900,
		centerZ = -520,
		sizeXZ = 320,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 64,
		hillScale = 260,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C2",
		centerX = 3050,
		centerZ = -520,
		sizeXZ = 340,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 68,
		hillScale = 260,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C3",
		centerX = 3200,
		centerZ = -480,
		sizeXZ = 300,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 60,
		hillScale = 270,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C4",
		centerX = 3000,
		centerZ = -420,
		sizeXZ = 360,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 72,
		hillScale = 250,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C5",
		centerX = 2800,
		centerZ = -420,
		sizeXZ = 300,
		baseY = 9,
		thickness = 30,
		grid = 5,
		hillAmplitude = 60,
		hillScale = 260,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C6",
		centerX = 3150,
		centerZ = -360,
		sizeXZ = 320,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 64,
		hillScale = 260,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C7",
		centerX = 2920,
		centerZ = -340,
		sizeXZ = 280,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 56,
		hillScale = 270,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C8",
		centerX = 3050,
		centerZ = -240,
		sizeXZ = 380,
		baseY = 11,
		thickness = 30,
		grid = 2,
		hillAmplitude = 80,
		hillScale = 180,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C9",
		centerX = 3200,
		centerZ = -200,
		sizeXZ = 320,
		baseY = 11,
		thickness = 30,
		grid = 5,
		hillAmplitude = 60,
		hillScale = 200,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C10",
		centerX = 2900,
		centerZ = -200,
		sizeXZ = 300,
		baseY = 11,
		thickness = 30,
		grid = 6,
		hillAmplitude = 50,
		hillScale = 210,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C11",
		centerX = 3300,
		centerZ = -80,
		sizeXZ = 340,
		baseY = 11,
		thickness = 30,
		grid = 5,
		hillAmplitude = 70,
		hillScale = 210,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C12",
		centerX = 3000,
		centerZ = -40,
		sizeXZ = 360,
		baseY = 12,
		thickness = 30,
		grid = 6,
		hillAmplitude = 80,
		hillScale = 190,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C13",
		centerX = 3150,
		centerZ = 60,
		sizeXZ = 340,
		baseY = 12,
		thickness = 30,
		grid = 6,
		hillAmplitude = 70,
		hillScale = 190,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C14",
		centerX = 3000,
		centerZ = 160,
		sizeXZ = 360,
		baseY = 12,
		thickness = 30,
		grid = 8,
		hillAmplitude = 80,
		hillScale = 180,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C15",
		centerX = 2850,
		centerZ = 220,
		sizeXZ = 300,
		baseY = 11,
		thickness = 30,
		grid = 5,
		hillAmplitude = 50,
		hillScale = 190,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C16",
		centerX = 3120,
		centerZ = 300,
		sizeXZ = 320,
		baseY = 11,
		thickness = 30,
		grid = 5,
		hillAmplitude = 60,
		hillScale = 190,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C17",
		centerX = 3000,
		centerZ = 380,
		sizeXZ = 300,
		baseY = 11,
		thickness = 30,
		grid = 8,
		hillAmplitude = 50,
		hillScale = 180,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C18",
		centerX = 3180,
		centerZ = 470,
		sizeXZ = 240,
		baseY = 12,
		thickness = 30,
		grid = 2,
		hillAmplitude = 140,
		hillScale = 160,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.Basalt,
	},
	{
		name = "ContinentKyushu_C19",
		centerX = 2760,
		centerZ = -60,
		sizeXZ = 220,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 70,
		hillScale = 220,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C20",
		centerX = 2700,
		centerZ = 40,
		sizeXZ = 200,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 15,
		hillScale = 220,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C21",
		centerX = 2680,
		centerZ = 140,
		sizeXZ = 180,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 15,
		hillScale = 220,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C22",
		centerX = 2750,
		centerZ = 220,
		sizeXZ = 200,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 15,
		hillScale = 220,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C23",
		centerX = 3350,
		centerZ = 40,
		sizeXZ = 320,
		baseY = 10,
		thickness = 30,
		grid = 5,
		hillAmplitude = 15,
		hillScale = 260,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "ContinentKyushu_C24",
		centerX = 3420,
		centerZ = 160,
		sizeXZ = 300,
		baseY = 9,
		thickness = 30,
		grid = 5,
		hillAmplitude = 15,
		hillScale = 270,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
}
