return {
	{
		name = "Town_01",
		centerX = 400,
		centerZ = 400,
		sizeXZ = 600,
		baseY = 300,
		thickness = 30,
		grid = 15,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Town_02",
		centerX = 400,
		centerZ = 100,
		sizeXZ = 200,
		baseY = 300,
		thickness = 30,
		grid = 15,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Town_03",
		centerX = 700,
		centerZ = 400,
		sizeXZ = 200,
		baseY = 300,
		thickness = 30,
		grid = 15,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Town_04",
		centerX = 400,
		centerZ = 700,
		sizeXZ = 200,
		baseY = 300,
		thickness = 30,
		grid = 15,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Town_05",
		centerX = 100,
		centerZ = 400,
		sizeXZ = 200,
		baseY = 300,
		thickness = 30,
		grid = 15,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.LeafyGrass,
	},
}
