return {

	{
		name = "Town2_01",
		centerX = 400,
		centerZ = 400,
		sizeXZ = 600,
		baseY = 30,
		thickness = 30,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		-- baseMaterial = Enum.Material.Cobblestone,
		-- baseMaterial = Enum.Material.LeafyGrass, 柔らかい緑（低い芝生）
		-- baseMaterial = Enum.Material.Grass, -- 芝生
		baseMaterial = Enum.Material.Ice, -- 芝生
	},
	{
		name = "Town2_02",
		centerX = 400,
		centerZ = 100,
		sizeXZ = 200,
		baseY = 30,
		thickness = 30,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.Ice,
	},
	{
		name = "Town2_03",
		centerX = 700,
		centerZ = 400,
		sizeXZ = 200,
		baseY = 30,
		thickness = 30,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.Ice,
	},
	{
		name = "Town2_04",
		centerX = 400,
		centerZ = 700,
		sizeXZ = 200,
		baseY = 30,
		thickness = 30,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.Ice,
	},
	{
		name = "Town2_05",
		centerX = 100,
		centerZ = 400,
		sizeXZ = 200,
		baseY = 30,
		thickness = 30,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.Ice,
	},
}
