return {

	{
		name = "Town_01",
		centerX = 400,
		centerZ = 400,
		sizeXZ = 600,
		baseY = 30,
		thickness = 30,
		grid = 2,
		hillAmplitude = 150,
		hillScale = 50,
		seed = 0,
		generateOcean = true,
		oceanRadius = 2000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Town_02",
		centerX = 400,
		centerZ = 100,
		sizeXZ = 200,
		baseY = 30,
		thickness = 30,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.Mud,
	},
	{
		name = "Town_03",
		centerX = 700,
		centerZ = 400,
		sizeXZ = 200,
		baseY = 30,
		thickness = 30,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.Asphalt,
	},
	{
		name = "Town_04",
		centerX = 400,
		centerZ = 700,
		sizeXZ = 200,
		baseY = 30,
		thickness = 30,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.Cobblestone,
	},
	{
		name = "Town_05",
		centerX = 100,
		centerZ = 400,
		sizeXZ = 200,
		baseY = 30,
		thickness = 30,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		oceanRadius = 0,
		baseMaterial = Enum.Material.Glacier,
	},
}
