-- ReplicatedStorage/TypingWords
-- タイピング用の単語リスト（多言語対応）

return {
	level_1 = {
		{word = "cat", ja = "猫", es = "gato", fr = "chat"},
		{word = "dog", ja = "犬", es = "perro", fr = "chien"},
		{word = "pen", ja = "ペン", es = "pluma", fr = "stylo"},
		{word = "cup", ja = "カップ", es = "taza", fr = "tasse"},
		{word = "sun", ja = "太陽", es = "sol", fr = "soleil"},
		{word = "red", ja = "赤", es = "rojo", fr = "rouge"},
		{word = "big", ja = "大きい", es = "grande", fr = "grand"},
		{word = "run", ja = "走る", es = "correr", fr = "courir"},
		{word = "fly", ja = "飛ぶ", es = "volar", fr = "voler"},
		{word = "eat", ja = "食べる", es = "comer", fr = "manger"},
	},
	level_2 = {
		{word = "apple", ja = "りんご", es = "manzana", fr = "pomme"},
		{word = "house", ja = "家", es = "casa", fr = "maison"},
		{word = "water", ja = "水", es = "agua", fr = "eau"},
		{word = "sleep", ja = "眠る", es = "dormir", fr = "dormir"},
		{word = "happy", ja = "幸せ", es = "feliz", fr = "heureux"},
		{word = "green", ja = "緑", es = "verde", fr = "vert"},
		{word = "river", ja = "川", es = "río", fr = "rivière"},
		{word = "night", ja = "夜", es = "noche", fr = "nuit"},
		{word = "music", ja = "音楽", es = "música", fr = "musique"},
		{word = "stone", ja = "石", es = "piedra", fr = "pierre"},
	},
	level_3 = {
		{word = "banana", ja = "バナナ", es = "plátano", fr = "banane"},
		{word = "orange", ja = "オレンジ", es = "naranja", fr = "orange"},
		{word = "yellow", ja = "黄色", es = "amarillo", fr = "jaune"},
		{word = "purple", ja = "紫", es = "morado", fr = "violet"},
		{word = "animal", ja = "動物", es = "animal", fr = "animal"},
		{word = "window", ja = "窓", es = "ventana", fr = "fenêtre"},
		{word = "garden", ja = "庭", es = "jardín", fr = "jardin"},
		{word = "bridge", ja = "橋", es = "puente", fr = "pont"},
		{word = "planet", ja = "惑星", es = "planeta", fr = "planète"},
		{word = "forest", ja = "森", es = "bosque", fr = "forêt"},
	},
	level_4 = {
		{word = "monday", ja = "月曜日", es = "lunes", fr = "lundi"},
		{word = "sunday", ja = "日曜日", es = "domingo", fr = "dimanche"},
		{word = "friday", ja = "金曜日", es = "viernes", fr = "vendredi"},
		{word = "winter", ja = "冬", es = "invierno", fr = "hiver"},
		{word = "summer", ja = "夏", es = "verano", fr = "été"},
		{word = "spring", ja = "春", es = "primavera", fr = "printemps"},
		{word = "autumn", ja = "秋", es = "otoño", fr = "automne"},
		{word = "dragon", ja = "ドラゴン", es = "dragón", fr = "dragon"},
		{word = "castle", ja = "城", es = "castillo", fr = "château"},
		{word = "warrior", ja = "戦士", es = "guerrero", fr = "guerrier"},
	},
	level_5 = {
		{word = "mountain", ja = "山", es = "montaña", fr = "montagne"},
		{word = "keyboard", ja = "キーボード", es = "teclado", fr = "clavier"},
		{word = "computer", ja = "コンピュータ", es = "computadora", fr = "ordinateur"},
		{word = "adventure", ja = "冒険", es = "aventura", fr = "aventure"},
		{word = "beautiful", ja = "美しい", es = "hermoso", fr = "beau"},
		{word = "champion", ja = "チャンピオン", es = "campeón", fr = "champion"},
		{word = "treasure", ja = "宝物", es = "tesoro", fr = "trésor"},
		{word = "butterfly", ja = "蝶", es = "mariposa", fr = "papillon"},
		{word = "elephant", ja = "象", es = "elefante", fr = "éléphant"},
		{word = "challenge", ja = "挑戦", es = "desafío", fr = "défi"},
	},
}